### ISSUE TITLE
waze not open

### ISSUE THREAD

**Issue by roysG** [adaltojunior86/cordova-waze-navigator#1]
Firsatble thank you for your time for building this this awesome plugin.

I am using your plugin like that:

window.WazeNavigator.navigateByPosition({lat:32.020936,lng:34.73915499999998})

but nothing happen.

**Comment by adaltojunior86** [comment]
Hi, I apologize for the delay in answering. Did you tried this way: WazeNavigator.navigateByPosition({lat:32.020936,lng:34.73915499999998}); ?
